/** Each nation's own page theme, measured off its flag.
 *
 * GENERATED by scripts/make-flag-palette.py from scripts/flag-pixels.txt.
 * Do not edit by hand: edit the script and re-run it.
 *
 * `ground` replaces the site's terracotta canvas for the whole country
 * page -- band, body and footer. It is the nation's hue at the site
 * canvas's own chroma, darkened until every text token the site paints
 * straight onto a canvas (white/90, white/92 and --gold-on-canvas) clears
 * WCAG AA, measured with the grain tile, the band's warm wash and the two
 * blooms below all composited on. The ratio on each line is that
 * measurement at the page's brightest point, not an estimate.
 *
 * `band` is the head band, deliberately darker than the ground: the whole
 * flag is laid across it at `flagAlpha`, and a ground already sitting at
 * the 4.5:1 floor has no room to give. `flagAlpha` is then the MOST of the
 * flag that fits, walked down in 1% steps from a 55% cap until the band's
 * text clears AA against the flag's single brightest pixel -- the worst
 * point of the worst stripe, not the flag's average.
 *
 * `motif` is the SHAPE of the flag rather than its colour -- horizontal,
 * vertical, diagonal, cross or emblem, read off where the flag's edges
 * point. The page wears it as a faint ruling, so two nations with similar
 * colours still read as different places. Derived, never chosen: a
 * hand-picked national motif would be a guess about someone else's
 * culture, and this can only ever describe the flag already on the page.
 *
 * `accent` is the same flag colour left vivid, darkened only as far as
 * being readable ON a panel needs; `stripes` and `glow` are the flag's
 * colours untouched, since nothing is painted on top of them.
 *
 * Only lightness ever moves, so the hue that makes a colour recognisable
 * survives every clamp. */
export type FlagPalette = {
  /** How the flag is built, for the page's own ruling. */
  motif: "horizontal" | "vertical" | "diagonal" | "cross" | "emblem";
  /** Page canvas, already AA-safe under everything the site paints on one. */
  ground: string;
  /** Head band, darker than the ground to make room for the flag. */
  band: string;
  /** How much of the flag the band can show, 0-1. */
  flagAlpha: number;
  /** Vivid flag colour for rules and edges on the light panels. */
  accent: string;
  /** Up to three flag colours, largest area first, unclamped. */
  stripes: string[];
  /** Two flag colours for the page's ambient blooms, unclamped. */
  glow: string[];
};

/** Keyed by ISO 3166-1 alpha-2, the code the flag SVG is named by. Use
 * `countryPalette()` in ./flags to reach one from a nation's IOC code. */
export const FLAG_PALETTE: Record<string, FlagPalette> = {
  // #0018a8: ground 4.54:1, band 4.56:1 with 24% of the flag showing (brightest pixel #ffffff), accent 11.34:1
  ad: {
    motif: "vertical",
    ground: "#324d89",
    band: "#0b111f",
    flagAlpha: 0.24,
    accent: "#0018a8",
    stripes: ["#0018a8", "#d0103a", "#fedf00"],
    glow: ["#d0103a", "#fedf00"],
  },
  // #ff0000: ground 4.54:1, band 4.6:1 with 29% of the flag showing (brightest pixel #ffffff), accent 4.59:1
  ae: {
    motif: "horizontal",
    ground: "#8f443a",
    band: "#1d0c0a",
    flagAlpha: 0.29,
    accent: "#e10000",
    stripes: ["#ff0000", "#00732f", "#ffffff"],
    glow: ["#00732f", "#00732f"],
  },
  // #ff0000: ground 4.57:1, band 5.21:1 with 55% of the flag showing (brightest pixel #ff0000), accent 4.59:1
  al: {
    motif: "diagonal",
    ground: "#893e34",
    band: "#1d0c0a",
    flagAlpha: 0.55,
    accent: "#e10000",
    stripes: ["#ff0000", "#000001"],
    glow: ["#ff0000", "#ff0000"],
  },
  // #0033a0: ground 4.55:1, band 4.53:1 with 38% of the flag showing (brightest pixel #f2a800), accent 9.71:1
  am: {
    motif: "horizontal",
    ground: "#35538f",
    band: "#0a111f",
    flagAlpha: 0.38,
    accent: "#0033a0",
    stripes: ["#d90012", "#0033a0", "#f2a800"],
    glow: ["#d90012", "#f2a800"],
  },
  // #74acdf: ground 4.61:1, band 4.55:1 with 22% of the flag showing (brightest pixel #ffffff), accent 4.69:1
  ar: {
    motif: "horizontal",
    ground: "#104b78",
    band: "#06131e",
    flagAlpha: 0.22,
    accent: "#3b72a1",
    stripes: ["#74acdf", "#ffffff"],
    glow: ["#74acdf", "#74acdf"],
  },
  // #c8102e: ground 4.57:1, band 4.54:1 with 31% of the flag showing (brightest pixel #ffffff), accent 5.39:1
  at: {
    motif: "horizontal",
    ground: "#8c403f",
    band: "#1d0c0b",
    flagAlpha: 0.31,
    accent: "#c8102e",
    stripes: ["#c8102e", "#ffffff"],
    glow: ["#c8102e", "#c8102e"],
  },
  // #00008b: ground 4.53:1, band 4.53:1 with 31% of the flag showing (brightest pixel #ffffff), accent 14.01:1
  au: {
    motif: "diagonal",
    ground: "#415e9c",
    band: "#0b111f",
    flagAlpha: 0.31,
    accent: "#00008b",
    stripes: ["#00008b", "#ffffff", "#ff0000"],
    glow: ["#ff0000", "#ff0000"],
  },
  // #ed2939: ground 4.59:1, band 4.51:1 with 25% of the flag showing (brightest pixel #ffffff), accent 4.57:1
  az: {
    motif: "horizontal",
    ground: "#833735",
    band: "#1d0c0b",
    flagAlpha: 0.25,
    accent: "#de0e2c",
    stripes: ["#3f9c35", "#00b9e4", "#ed2939"],
    glow: ["#3f9c35", "#00b9e4"],
  },
  // #000099: ground 4.53:1, band 4.57:1 with 18% of the flag showing (brightest pixel #ffffff), accent 13.18:1
  ba: {
    motif: "diagonal",
    ground: "#253f7a",
    band: "#0b111f",
    flagAlpha: 0.18,
    accent: "#000099",
    stripes: ["#000099", "#ffcc00"],
    glow: ["#ffcc00", "#ffcc00"],
  },
  // #00267f: ground 4.55:1, band 4.54:1 with 23% of the flag showing (brightest pixel #ffc726), accent 12.15:1
  bb: {
    motif: "vertical",
    ground: "#233f79",
    band: "#0a111f",
    flagAlpha: 0.23,
    accent: "#00267f",
    stripes: ["#00267f", "#ffc726"],
    glow: ["#ffc726", "#ffc726"],
  },
  // #f31830: ground 4.55:1, band 4.55:1 with 20% of the flag showing (brightest pixel #ffd90c), accent 4.58:1
  be: {
    motif: "vertical",
    ground: "#6d2322",
    band: "#1d0c0b",
    flagAlpha: 0.2,
    accent: "#e0001e",
    stripes: ["#000001", "#f31830", "#ffd90c"],
    glow: ["#ffd90c", "#ffd90c"],
  },
  // #de0000: ground 4.58:1, band 4.56:1 with 22% of the flag showing (brightest pixel #fff300), accent 4.69:1
  bf: {
    motif: "horizontal",
    ground: "#762d24",
    band: "#1d0c0a",
    flagAlpha: 0.22,
    accent: "#de0000",
    stripes: ["#de0000", "#35a100", "#fff300"],
    glow: ["#35a100", "#fff300"],
  },
  // #d62612: ground 4.55:1, band 4.53:1 with 27% of the flag showing (brightest pixel #ffffff), accent 4.64:1
  bg: {
    motif: "horizontal",
    ground: "#893e33",
    band: "#1d0c09",
    flagAlpha: 0.27,
    accent: "#d62612",
    stripes: ["#ffffff", "#00966e", "#d62612"],
    glow: ["#00966e", "#00966e"],
  },
  // #ce1126: ground 4.55:1, band 4.52:1 with 31% of the flag showing (brightest pixel #ffffff), accent 5.15:1
  bh: {
    motif: "diagonal",
    ground: "#8c403c",
    band: "#1d0c0b",
    flagAlpha: 0.31,
    accent: "#ce1126",
    stripes: ["#ce1126", "#ffffff"],
    glow: ["#ce1126", "#ce1126"],
  },
  // #cf0921: ground 4.57:1, band 4.6:1 with 24% of the flag showing (brightest pixel #ffffff), accent 5.18:1
  bi: {
    motif: "diagonal",
    ground: "#833733",
    band: "#1d0c0b",
    flagAlpha: 0.24,
    accent: "#cf0921",
    stripes: ["#ffffff", "#cf0921", "#18b637"],
    glow: ["#18b637", "#18b637"],
  },
  // #319400: ground 4.51:1, band 4.5:1 with 28% of the flag showing (brightest pixel #ffd600), accent 4.58:1
  bj: {
    motif: "cross",
    ground: "#28571a",
    band: "#0a1508",
    flagAlpha: 0.28,
    accent: "#188100",
    stripes: ["#319400", "#ffd600", "#de2110"],
    glow: ["#ffd600", "#de2110"],
  },
  // #ce132b: ground 4.54:1, band 4.51:1 with 31% of the flag showing (brightest pixel #ffffff), accent 5.13:1
  bm: {
    motif: "horizontal",
    ground: "#8c403d",
    band: "#1d0c0b",
    flagAlpha: 0.31,
    accent: "#ce132b",
    stripes: ["#ce132b", "#fefefe"],
    glow: ["#ce132b", "#ce132b"],
  },
  // #229e45: ground 4.52:1, band 4.58:1 with 23% of the flag showing (brightest pixel #ffffff), accent 4.55:1
  br: {
    motif: "diagonal",
    ground: "#155926",
    band: "#08150a",
    flagAlpha: 0.23,
    accent: "#008229",
    stripes: ["#229e45", "#f8e509", "#2b49a3"],
    glow: ["#f8e509", "#2b49a3"],
  },
  // #08ced6: ground 4.6:1, band 4.55:1 with 18% of the flag showing (brightest pixel #ffe900), accent 4.57:1
  bs: {
    motif: "horizontal",
    ground: "#00434a",
    band: "#001517",
    flagAlpha: 0.18,
    accent: "#007c84",
    stripes: ["#08ced6", "#000001", "#ffe900"],
    glow: ["#ffe900", "#ffe900"],
  },
  // #00cbff: ground 4.56:1, band 4.5:1 with 22% of the flag showing (brightest pixel #ffffff), accent 4.69:1
  bw: {
    motif: "horizontal",
    ground: "#004c6c",
    band: "#02141b",
    flagAlpha: 0.22,
    accent: "#0075a6",
    stripes: ["#00cbff", "#000001", "#ffffff"],
    glow: ["#00cbff", "#00cbff"],
  },
  // #ce1720: ground 4.62:1, band 4.54:1 with 29% of the flag showing (brightest pixel #ffffff), accent 5.11:1
  by: {
    motif: "diagonal",
    ground: "#8c403a",
    band: "#1d0c0a",
    flagAlpha: 0.29,
    accent: "#ce1720",
    stripes: ["#ce1720", "#007c30"],
    glow: ["#007c30", "#007c30"],
  },
  // #d52b1e: ground 4.52:1, band 4.55:1 with 29% of the flag showing (brightest pixel #ffffff), accent 4.59:1
  ca: {
    motif: "vertical",
    ground: "#893e34",
    band: "#1d0c0a",
    flagAlpha: 0.29,
    accent: "#d52b1e",
    stripes: ["#d52b1e", "#ffffff"],
    glow: ["#d52b1e", "#d52b1e"],
  },
  // #ff0000: ground 4.57:1, band 4.59:1 with 30% of the flag showing (brightest pixel #ffffff), accent 4.59:1
  ch: {
    motif: "cross",
    ground: "#893e34",
    band: "#1d0c0a",
    flagAlpha: 0.3,
    accent: "#e10000",
    stripes: ["#ff0000", "#ffffff"],
    glow: ["#ff0000", "#ff0000"],
  },
  // #00cd00: ground 4.54:1, band 4.55:1 with 21% of the flag showing (brightest pixel #ffffff), accent 4.57:1
  ci: {
    motif: "vertical",
    ground: "#1c5219",
    band: "#091509",
    flagAlpha: 0.21,
    accent: "#008200",
    stripes: ["#ff9a00", "#ffffff", "#00cd00"],
    glow: ["#ff9a00", "#ff9a00"],
  },
  // #d52b1e: ground 4.58:1, band 4.51:1 with 33% of the flag showing (brightest pixel #ffffff), accent 4.59:1
  cl: {
    motif: "horizontal",
    ground: "#96493f",
    band: "#1d0c0a",
    flagAlpha: 0.33,
    accent: "#d52b1e",
    stripes: ["#d52b1e", "#ffffff", "#0039a6"],
    glow: ["#0039a6", "#0039a6"],
  },
  // #ce1126: ground 4.62:1, band 4.58:1 with 28% of the flag showing (brightest pixel #fcd116), accent 5.15:1
  cm: {
    motif: "vertical",
    ground: "#7c322f",
    band: "#1d0c0b",
    flagAlpha: 0.28,
    accent: "#ce1126",
    stripes: ["#fcd116", "#007a5e", "#ce1126"],
    glow: ["#fcd116", "#007a5e"],
  },
  // #ee1c25: ground 4.61:1, band 4.59:1 with 30% of the flag showing (brightest pixel #ffff00), accent 4.5:1
  cn: {
    motif: "vertical",
    ground: "#863b34",
    band: "#1d0c0a",
    flagAlpha: 0.3,
    accent: "#e30019",
    stripes: ["#ee1c25"],
    glow: ["#ee1c25", "#ee1c25"],
  },
  // #ffe800: ground 4.55:1, band 4.58:1 with 37% of the flag showing (brightest pixel #ffe800), accent 4.5:1
  co: {
    motif: "horizontal",
    ground: "#6d6200",
    band: "#141203",
    flagAlpha: 0.37,
    accent: "#876e00",
    stripes: ["#ffe800", "#00148e", "#da0010"],
    glow: ["#00148e", "#da0010"],
  },
  // #0000b4: ground 4.62:1, band 4.54:1 with 32% of the flag showing (brightest pixel #ffffff), accent 11.6:1
  cr: {
    motif: "horizontal",
    ground: "#415e9c",
    band: "#0b111f",
    flagAlpha: 0.32,
    accent: "#0000b4",
    stripes: ["#ffffff", "#0000b4", "#d90000"],
    glow: ["#d90000", "#d90000"],
  },
  // #002a8f: ground 4.51:1, band 4.54:1 with 31% of the flag showing (brightest pixel #ffffff), accent 11.13:1
  cu: {
    motif: "horizontal",
    ground: "#405f9c",
    band: "#0a111f",
    flagAlpha: 0.31,
    accent: "#002a8f",
    stripes: ["#002a8f", "#cb1515", "#ffffff"],
    glow: ["#cb1515", "#cb1515"],
  },
  // #081873: ground 4.57:1, band 4.56:1 with 28% of the flag showing (brightest pixel #ffffff), accent 13.86:1
  cv: {
    motif: "horizontal",
    ground: "#3c5592",
    band: "#0b111f",
    flagAlpha: 0.28,
    accent: "#081873",
    stripes: ["#081873", "#ffffff", "#de3929"],
    glow: ["#de3929", "#de3929"],
  },
  // #d47600: ground 4.53:1, band 4.59:1 with 24% of the flag showing (brightest pixel #ffffff), accent 4.5:1
  cy: {
    motif: "diagonal",
    ground: "#753c00",
    band: "#1b0e04",
    flagAlpha: 0.24,
    accent: "#b25700",
    stripes: ["#ffffff", "#d47600"],
    glow: ["#d47600", "#d47600"],
  },
  // #d7141a: ground 4.61:1, band 4.52:1 with 32% of the flag showing (brightest pixel #ffffff), accent 4.8:1
  cz: {
    motif: "diagonal",
    ground: "#93463e",
    band: "#1d0c0a",
    flagAlpha: 0.32,
    accent: "#d7141a",
    stripes: ["#ffffff", "#d7141a", "#11457e"],
    glow: ["#11457e", "#11457e"],
  },
  // #ff0000: ground 4.62:1, band 4.54:1 with 22% of the flag showing (brightest pixel #ffcc00), accent 4.59:1
  de: {
    motif: "horizontal",
    ground: "#6d241c",
    band: "#1d0c0a",
    flagAlpha: 0.22,
    accent: "#e10000",
    stripes: ["#000001", "#ff0000", "#ffcc00"],
    glow: ["#ffcc00", "#ffcc00"],
  },
  // #00cc00: ground 4.59:1, band 4.57:1 with 23% of the flag showing (brightest pixel #fffefe), accent 4.62:1
  dj: {
    motif: "diagonal",
    ground: "#1f551c",
    band: "#091509",
    flagAlpha: 0.23,
    accent: "#008100",
    stripes: ["#6699ff", "#00cc00", "#fffefe"],
    glow: ["#6699ff", "#6699ff"],
  },
  // #c8102e: ground 4.57:1, band 4.54:1 with 31% of the flag showing (brightest pixel #ffffff), accent 5.39:1
  dk: {
    motif: "cross",
    ground: "#8c403f",
    band: "#1d0c0b",
    flagAlpha: 0.31,
    accent: "#c8102e",
    stripes: ["#c8102e", "#ffffff"],
    glow: ["#c8102e", "#c8102e"],
  },
  // #108c00: ground 4.52:1, band 4.52:1 with 29% of the flag showing (brightest pixel #ffffff), accent 4.55:1
  dm: {
    motif: "horizontal",
    ground: "#32662c",
    band: "#0a1508",
    flagAlpha: 0.29,
    accent: "#008300",
    stripes: ["#108c00", "#e72910", "#ffffff"],
    glow: ["#e72910", "#e72910"],
  },
  // #ce1126: ground 4.57:1, band 4.53:1 with 34% of the flag showing (brightest pixel #ffffff), accent 5.15:1
  do: {
    motif: "horizontal",
    ground: "#994b47",
    band: "#1d0c0b",
    flagAlpha: 0.34,
    accent: "#ce1126",
    stripes: ["#ce1126", "#002d62", "#ffffff"],
    glow: ["#002d62", "#002d62"],
  },
  // #006233: ground 4.55:1, band 4.55:1 with 30% of the flag showing (brightest pixel #ffffff), accent 6.88:1
  dz: {
    motif: "vertical",
    ground: "#18683b",
    band: "#06150b",
    flagAlpha: 0.3,
    accent: "#006233",
    stripes: ["#ffffff", "#006233"],
    glow: ["#006233", "#006233"],
  },
  // #ffe800: ground 4.55:1, band 4.57:1 with 33% of the flag showing (brightest pixel #ffffff), accent 4.5:1
  ec: {
    motif: "vertical",
    ground: "#6d6200",
    band: "#141203",
    flagAlpha: 0.33,
    accent: "#876e00",
    stripes: ["#ffe800", "#da0010", "#00148e"],
    glow: ["#da0010", "#00148e"],
  },
  // #1791ff: ground 4.53:1, band 4.58:1 with 25% of the flag showing (brightest pixel #ffffff), accent 4.55:1
  ee: {
    motif: "horizontal",
    ground: "#1d5187",
    band: "#08121e",
    flagAlpha: 0.25,
    accent: "#006ed9",
    stripes: ["#1791ff", "#000001", "#ffffff"],
    glow: ["#1791ff", "#1791ff"],
  },
  // #ce1126: ground 4.55:1, band 4.52:1 with 31% of the flag showing (brightest pixel #ffffff), accent 5.15:1
  eg: {
    motif: "horizontal",
    ground: "#8c403c",
    band: "#1d0c0b",
    flagAlpha: 0.31,
    accent: "#ce1126",
    stripes: ["#ce1126", "#000001", "#ffffff"],
    glow: ["#ce1126", "#ce1126"],
  },
  // #be0027: ground 4.52:1, band 4.55:1 with 25% of the flag showing (brightest pixel #f3e295), accent 5.98:1
  er: {
    motif: "diagonal",
    ground: "#7c3131",
    band: "#1d0c0b",
    flagAlpha: 0.25,
    accent: "#be0027",
    stripes: ["#be0027", "#239e46", "#b4d7f4"],
    glow: ["#239e46", "#b4d7f4"],
  },
  // #aa151b: ground 4.62:1, band 4.51:1 with 25% of the flag showing (brightest pixel #cccccc), accent 6.79:1
  es: {
    motif: "horizontal",
    ground: "#702622",
    band: "#1d0c0a",
    flagAlpha: 0.25,
    accent: "#aa151b",
    stripes: ["#aa151b", "#f1bf00"],
    glow: ["#f1bf00", "#f1bf00"],
  },
  // #298c08: ground 4.56:1, band 4.58:1 with 29% of the flag showing (brightest pixel #ffc621), accent 4.68:1
  et: {
    motif: "horizontal",
    ground: "#26581c",
    band: "#0a1508",
    flagAlpha: 0.29,
    accent: "#188000",
    stripes: ["#298c08", "#ef2118", "#ffc621"],
    glow: ["#ef2118", "#ffc621"],
  },
  // #002f6c: ground 4.53:1, band 4.59:1 with 33% of the flag showing (brightest pixel #ffffff), accent 11.85:1
  fi: {
    motif: "cross",
    ground: "#3b639e",
    band: "#09121f",
    flagAlpha: 0.33,
    accent: "#002f6c",
    stripes: ["#ffffff", "#002f6c"],
    glow: ["#002f6c", "#002f6c"],
  },
  // #68bfe5: ground 4.54:1, band 4.58:1 with 31% of the flag showing (brightest pixel #ffffff), accent 4.62:1
  fj: {
    motif: "horizontal",
    ground: "#007093",
    band: "#03141c",
    flagAlpha: 0.31,
    accent: "#13789b",
    stripes: ["#68bfe5", "#c8102e", "#fefefe"],
    glow: ["#c8102e", "#c8102e"],
  },
  // #000091: ground 4.59:1, band 4.51:1 with 32% of the flag showing (brightest pixel #ffffff), accent 13.66:1
  fr: {
    motif: "vertical",
    ground: "#415e9c",
    band: "#0b111f",
    flagAlpha: 0.32,
    accent: "#000091",
    stripes: ["#000091", "#e1000f", "#ffffff"],
    glow: ["#e1000f", "#e1000f"],
  },
  // #36a100: ground 4.59:1, band 4.57:1 with 25% of the flag showing (brightest pixel #ffe700), accent 4.61:1
  ga: {
    motif: "horizontal",
    ground: "#225214",
    band: "#0a1508",
    flagAlpha: 0.25,
    accent: "#028200",
    stripes: ["#36a100", "#ffe700", "#006dbc"],
    glow: ["#ffe700", "#006dbc"],
  },
  // #c8102e: ground 4.5:1, band 4.5:1 with 35% of the flag showing (brightest pixel #ffffff), accent 5.39:1
  gb: {
    motif: "diagonal",
    ground: "#9c4e4d",
    band: "#1d0c0b",
    flagAlpha: 0.35,
    accent: "#c8102e",
    stripes: ["#c8102e", "#ffffff", "#012169"],
    glow: ["#012169", "#012169"],
  },
  // #ce1126: ground 4.62:1, band 4.58:1 with 28% of the flag showing (brightest pixel #fcd116), accent 5.15:1
  gd: {
    motif: "horizontal",
    ground: "#7c322f",
    band: "#1d0c0b",
    flagAlpha: 0.28,
    accent: "#ce1126",
    stripes: ["#ce1126", "#fcd116", "#007a5e"],
    glow: ["#fcd116", "#007a5e"],
  },
  // #ff0000: ground 4.57:1, band 4.59:1 with 30% of the flag showing (brightest pixel #ffffff), accent 4.59:1
  ge: {
    motif: "cross",
    ground: "#893e34",
    band: "#1d0c0a",
    flagAlpha: 0.3,
    accent: "#e10000",
    stripes: ["#ffffff", "#ff0000"],
    glow: ["#ff0000", "#ff0000"],
  },
  // #ce1126: ground 4.55:1, band 4.56:1 with 29% of the flag showing (brightest pixel #fcd116), accent 5.15:1
  gh: {
    motif: "horizontal",
    ground: "#803431",
    band: "#1d0c0b",
    flagAlpha: 0.29,
    accent: "#ce1126",
    stripes: ["#ce1126", "#006b3f", "#fcd116"],
    glow: ["#006b3f", "#fcd116"],
  },
  // #000099: ground 4.57:1, band 4.59:1 with 29% of the flag showing (brightest pixel #ffffff), accent 13.18:1
  gm: {
    motif: "horizontal",
    ground: "#3c5895",
    band: "#0b111f",
    flagAlpha: 0.29,
    accent: "#000099",
    stripes: ["#000099", "#ff0000", "#009900"],
    glow: ["#ff0000", "#009900"],
  },
  // #ff0000: ground 4.52:1, band 4.52:1 with 22% of the flag showing (brightest pixel #ffff00), accent 4.59:1
  gn: {
    motif: "vertical",
    ground: "#793027",
    band: "#1d0c0a",
    flagAlpha: 0.22,
    accent: "#e10000",
    stripes: ["#ff0000", "#009900", "#ffff00"],
    glow: ["#009900", "#ffff00"],
  },
  // #0d5eaf: ground 4.62:1, band 4.6:1 with 29% of the flag showing (brightest pixel #ffffff), accent 5.94:1
  gr: {
    motif: "horizontal",
    ground: "#2a5991",
    band: "#08121f",
    flagAlpha: 0.29,
    accent: "#0d5eaf",
    stripes: ["#0d5eaf", "#ffffff"],
    glow: ["#0d5eaf", "#0d5eaf"],
  },
  // #4997d0: ground 4.54:1, band 4.58:1 with 24% of the flag showing (brightest pixel #ffffff), accent 4.55:1
  gt: {
    motif: "vertical",
    ground: "#005484",
    band: "#05131e",
    flagAlpha: 0.24,
    accent: "#2375ac",
    stripes: ["#4997d0", "#ffffff"],
    glow: ["#4997d0", "#4997d0"],
  },
  // #399408: ground 4.61:1, band 4.56:1 with 23% of the flag showing (brightest pixel #ffffff), accent 4.54:1
  gy: {
    motif: "diagonal",
    ground: "#275416",
    band: "#0b1508",
    flagAlpha: 0.23,
    accent: "#248100",
    stripes: ["#399408", "#de2110", "#ffde08"],
    glow: ["#de2110", "#ffde08"],
  },
  // #171796: ground 4.5:1, band 4.53:1 with 31% of the flag showing (brightest pixel #ffffff), accent 12.03:1
  hr: {
    motif: "horizontal",
    ground: "#485c9c",
    band: "#0c111f",
    flagAlpha: 0.31,
    accent: "#171796",
    stripes: ["#ff0000", "#171796", "#ffffff"],
    glow: ["#ff0000", "#ff0000"],
  },
  // #00209f: ground 4.62:1, band 4.53:1 with 31% of the flag showing (brightest pixel #ffffff), accent 11.27:1
  ht: {
    motif: "horizontal",
    ground: "#3f5b99",
    band: "#0b111f",
    flagAlpha: 0.31,
    accent: "#00209f",
    stripes: ["#00209f", "#d21034"],
    glow: ["#d21034", "#d21034"],
  },
  // #d43516: ground 4.61:1, band 4.53:1 with 27% of the flag showing (brightest pixel #ffffff), accent 4.65:1
  hu: {
    motif: "horizontal",
    ground: "#863c2d",
    band: "#1d0c09",
    flagAlpha: 0.27,
    accent: "#d03111",
    stripes: ["#d43516", "#ffffff", "#388d00"],
    glow: ["#388d00", "#388d00"],
  },
  // #ff7900: ground 4.59:1, band 4.51:1 with 27% of the flag showing (brightest pixel #ffffff), accent 4.52:1
  ie: {
    motif: "vertical",
    ground: "#824115",
    band: "#1c0d06",
    flagAlpha: 0.27,
    accent: "#c64400",
    stripes: ["#009a49", "#ff7900", "#ffffff"],
    glow: ["#009a49", "#009a49"],
  },
  // #0038b8: ground 4.52:1, band 4.57:1 with 32% of the flag showing (brightest pixel #ffffff), accent 8.52:1
  il: {
    motif: "horizontal",
    ground: "#405f9c",
    band: "#0a111f",
    flagAlpha: 0.32,
    accent: "#0038b8",
    stripes: ["#ffffff", "#0038b8"],
    glow: ["#0038b8", "#0038b8"],
  },
  // #128807: ground 4.53:1, band 4.53:1 with 21% of the flag showing (brightest pixel #ffffff), accent 4.6:1
  in: {
    motif: "horizontal",
    ground: "#1d5219",
    band: "#0a1508",
    flagAlpha: 0.21,
    accent: "#028200",
    stripes: ["#ff9933", "#128807", "#ffffff"],
    glow: ["#ff9933", "#ff9933"],
  },
  // #da0000: ground 4.54:1, band 4.52:1 with 26% of the flag showing (brightest pixel #ffffff), accent 4.83:1
  ir: {
    motif: "horizontal",
    ground: "#863b31",
    band: "#1d0c0a",
    flagAlpha: 0.26,
    accent: "#da0000",
    stripes: ["#da0000", "#ffffff", "#239f40"],
    glow: ["#239f40", "#239f40"],
  },
  // #003897: ground 4.6:1, band 4.58:1 with 29% of the flag showing (brightest pixel #ffffff), accent 9.56:1
  is: {
    motif: "cross",
    ground: "#385995",
    band: "#0a121f",
    flagAlpha: 0.29,
    accent: "#003897",
    stripes: ["#003897", "#d72828", "#ffffff"],
    glow: ["#d72828", "#d72828"],
  },
  // #ce2b37: ground 4.61:1, band 4.58:1 with 27% of the flag showing (brightest pixel #ffffff), accent 4.78:1
  it: {
    motif: "vertical",
    ground: "#893d3b",
    band: "#1d0c0b",
    flagAlpha: 0.27,
    accent: "#ce2b37",
    stripes: ["#009246", "#ce2b37", "#ffffff"],
    glow: ["#009246", "#009246"],
  },
  // #009900: ground 4.54:1, band 4.52:1 with 22% of the flag showing (brightest pixel #ffcc00), accent 4.53:1
  jm: {
    motif: "diagonal",
    ground: "#124a10",
    band: "#091509",
    flagAlpha: 0.22,
    accent: "#008300",
    stripes: ["#ffcc00", "#009900", "#000001"],
    glow: ["#ffcc00", "#ffcc00"],
  },
  // #bc002d: ground 4.58:1, band 4.57:1 with 32% of the flag showing (brightest pixel #ffffff), accent 6.06:1
  jp: {
    motif: "emblem",
    ground: "#8f4244",
    band: "#1d0c0c",
    flagAlpha: 0.32,
    accent: "#bc002d",
    stripes: ["#ffffff", "#bc002d"],
    glow: ["#bc002d", "#bc002d"],
  },
  // #bb0000: ground 4.52:1, band 4.51:1 with 31% of the flag showing (brightest pixel #ffffff), accent 6.18:1
  ke: {
    motif: "horizontal",
    ground: "#93463c",
    band: "#1d0c0a",
    flagAlpha: 0.31,
    accent: "#bb0000",
    stripes: ["#000001", "#bb0000", "#006600"],
    glow: ["#006600", "#006600"],
  },
  // #c60000: ground 4.61:1, band 4.6:1 with 29% of the flag showing (brightest pixel #ffffff), accent 5.66:1
  kp: {
    motif: "horizontal",
    ground: "#8c4137",
    band: "#1d0c0a",
    flagAlpha: 0.29,
    accent: "#c60000",
    stripes: ["#c60000", "#3e5698", "#ffffff"],
    glow: ["#3e5698", "#3e5698"],
  },
  // #cd2e3a: ground 4.53:1, band 4.54:1 with 29% of the flag showing (brightest pixel #ffffff), accent 4.75:1
  kr: {
    motif: "emblem",
    ground: "#893d3c",
    band: "#1d0c0b",
    flagAlpha: 0.29,
    accent: "#cd2e3a",
    stripes: ["#ffffff", "#010101", "#cd2e3a"],
    glow: ["#cd2e3a", "#cd2e3a"],
  },
  // #000066: ground 4.52:1, band 4.56:1 with 31% of the flag showing (brightest pixel #ffffff), accent 16.14:1
  ky: {
    motif: "diagonal",
    ground: "#415e9c",
    band: "#0b111f",
    flagAlpha: 0.31,
    accent: "#000066",
    stripes: ["#000066", "#c8102e", "#ffffff"],
    glow: ["#c8102e", "#c8102e"],
  },
  // #00abc2: ground 4.5:1, band 4.59:1 with 17% of the flag showing (brightest pixel #ffec2d), accent 4.63:1
  kz: {
    motif: "diagonal",
    ground: "#004457",
    band: "#011519",
    flagAlpha: 0.17,
    accent: "#007990",
    stripes: ["#00abc2", "#ffec2d"],
    glow: ["#ffec2d", "#ffec2d"],
  },
  // #ee161f: ground 4.58:1, band 4.52:1 with 26% of the flag showing (brightest pixel #ffffff), accent 4.51:1
  lb: {
    motif: "horizontal",
    ground: "#863b34",
    band: "#1d0c0a",
    flagAlpha: 0.26,
    accent: "#e30011",
    stripes: ["#ee161f", "#ffffff", "#00a850"],
    glow: ["#00a850", "#00a850"],
  },
  // #65cfff: ground 4.58:1, band 4.56:1 with 18% of the flag showing (brightest pixel #ffffff), accent 4.63:1
  lc: {
    motif: "diagonal",
    ground: "#00486c",
    band: "#03141c",
    flagAlpha: 0.18,
    accent: "#0077a3",
    stripes: ["#65cfff", "#ffce00"],
    glow: ["#ffce00", "#ffce00"],
  },
  // #8d2029: ground 4.56:1, band 4.54:1 with 34% of the flag showing (brightest pixel #ffb700), accent 8.11:1
  lk: {
    motif: "vertical",
    ground: "#833738",
    band: "#1d0c0c",
    flagAlpha: 0.34,
    accent: "#8d2029",
    stripes: ["#8d2029", "#ffb700", "#005641"],
    glow: ["#ffb700", "#005641"],
  },
  // #cc0000: ground 4.69:1, band 4.51:1 with 37% of the flag showing (brightest pixel #ffffff), accent 5.39:1
  lr: {
    motif: "horizontal",
    ground: "#9c4f44",
    band: "#1d0c0a",
    flagAlpha: 0.37,
    accent: "#cc0000",
    stripes: ["#cc0000", "#ffffff", "#000066"],
    glow: ["#000066", "#000066"],
  },
  // #00209f: ground 4.6:1, band 4.52:1 with 27% of the flag showing (brightest pixel #ffffff), accent 11.27:1
  ls: {
    motif: "horizontal",
    ground: "#34508c",
    band: "#0b111f",
    flagAlpha: 0.27,
    accent: "#00209f",
    stripes: ["#ffffff", "#00209f", "#009543"],
    glow: ["#009543", "#009543"],
  },
  // #c1272d: ground 4.62:1, band 4.53:1 with 33% of the flag showing (brightest pixel #fdb913), accent 5.35:1
  lt: {
    motif: "horizontal",
    ground: "#803531",
    band: "#1d0c0b",
    flagAlpha: 0.33,
    accent: "#c1272d",
    stripes: ["#006a44", "#fdb913", "#c1272d"],
    glow: ["#006a44", "#fdb913"],
  },
  // #ed2939: ground 4.56:1, band 4.59:1 with 25% of the flag showing (brightest pixel #ffffff), accent 4.57:1
  lu: {
    motif: "horizontal",
    ground: "#863a38",
    band: "#1d0c0b",
    flagAlpha: 0.25,
    accent: "#de0e2c",
    stripes: ["#ed2939", "#ffffff", "#00a1de"],
    glow: ["#00a1de", "#00a1de"],
  },
  // #981e32: ground 4.56:1, band 4.59:1 with 31% of the flag showing (brightest pixel #ffffff), accent 7.5:1
  lv: {
    motif: "horizontal",
    ground: "#8f4247",
    band: "#1d0c0d",
    flagAlpha: 0.31,
    accent: "#981e32",
    stripes: ["#981e32", "#ffffff"],
    glow: ["#981e32", "#981e32"],
  },
  // #c1272d: ground 4.6:1, band 5.77:1 with 55% of the flag showing (brightest pixel #c1272d), accent 5.35:1
  ma: {
    motif: "diagonal",
    ground: "#893d39",
    band: "#1d0c0b",
    flagAlpha: 0.55,
    accent: "#c1272d",
    stripes: ["#c1272d"],
    glow: ["#c1272d", "#c1272d"],
  },
  // #00319c: ground 4.61:1, band 4.6:1 with 24% of the flag showing (brightest pixel #ffff00), accent 10.02:1
  md: {
    motif: "vertical",
    ground: "#2d4b86",
    band: "#0a111f",
    flagAlpha: 0.24,
    accent: "#00319c",
    stripes: ["#de2110", "#00319c", "#ffde00"],
    glow: ["#de2110", "#ffde00"],
  },
  // #c40308: ground 4.54:1, band 4.57:1 with 30% of the flag showing (brightest pixel #d4af3a), accent 5.72:1
  me: {
    motif: "horizontal",
    ground: "#762d25",
    band: "#1d0c0a",
    flagAlpha: 0.3,
    accent: "#c40308",
    stripes: ["#c40308", "#d3ae3b"],
    glow: ["#d3ae3b", "#d3ae3b"],
  },
  // #ee2737: ground 4.62:1, band 4.57:1 with 32% of the flag showing (brightest pixel #ffcd00), accent 4.57:1
  mu: {
    motif: "horizontal",
    ground: "#833735",
    band: "#1d0c0b",
    flagAlpha: 0.32,
    accent: "#df082a",
    stripes: ["#ee2737", "#151f6d", "#ffcd00"],
    glow: ["#151f6d", "#ffcd00"],
  },
  // #ce1126: ground 4.61:1, band 4.56:1 with 30% of the flag showing (brightest pixel #ffffff), accent 5.15:1
  mx: {
    motif: "vertical",
    ground: "#90433f",
    band: "#1d0c0b",
    flagAlpha: 0.3,
    accent: "#ce1126",
    stripes: ["#006847", "#ce1126", "#ffffff"],
    glow: ["#006847", "#006847"],
  },
  // #cc0000: ground 4.69:1, band 4.51:1 with 37% of the flag showing (brightest pixel #ffffff), accent 5.39:1
  my: {
    motif: "horizontal",
    ground: "#9c4f44",
    band: "#1d0c0a",
    flagAlpha: 0.37,
    accent: "#cc0000",
    stripes: ["#cc0000", "#ffffff", "#000066"],
    glow: ["#000066", "#000066"],
  },
  // #009a00: ground 4.55:1, band 4.59:1 with 24% of the flag showing (brightest pixel #ffffff), accent 4.65:1
  mz: {
    motif: "horizontal",
    ground: "#255b22",
    band: "#091509",
    flagAlpha: 0.24,
    accent: "#008100",
    stripes: ["#ffca00", "#009a00", "#ff0000"],
    glow: ["#ffca00", "#ff0000"],
  },
  // #c70000: ground 4.53:1, band 4.57:1 with 27% of the flag showing (brightest pixel #ffffff), accent 5.61:1
  na: {
    motif: "diagonal",
    ground: "#893e34",
    band: "#1d0c0a",
    flagAlpha: 0.27,
    accent: "#c70000",
    stripes: ["#c70000", "#38a100", "#3662a2"],
    glow: ["#38a100", "#3662a2"],
  },
  // #e05206: ground 4.59:1, band 4.55:1 with 25% of the flag showing (brightest pixel #ffffff), accent 4.57:1
  ne: {
    motif: "horizontal",
    ground: "#813b20",
    band: "#1d0d07",
    flagAlpha: 0.25,
    accent: "#cb3d00",
    stripes: ["#e05206", "#0db02b", "#ffffff"],
    glow: ["#0db02b", "#0db02b"],
  },
  // #008753: ground 4.53:1, band 4.57:1 with 27% of the flag showing (brightest pixel #ffffff), accent 4.53:1
  ng: {
    motif: "vertical",
    ground: "#00633b",
    band: "#05160c",
    flagAlpha: 0.27,
    accent: "#00814d",
    stripes: ["#008753", "#ffffff"],
    glow: ["#008753", "#008753"],
  },
  // #ae1c28: ground 4.55:1, band 4.57:1 with 31% of the flag showing (brightest pixel #ffffff), accent 6.42:1
  nl: {
    motif: "horizontal",
    ground: "#934543",
    band: "#1d0c0b",
    flagAlpha: 0.31,
    accent: "#ae1c28",
    stripes: ["#ae1c28", "#ffffff", "#21468b"],
    glow: ["#21468b", "#21468b"],
  },
  // #ed2939: ground 4.61:1, band 4.58:1 with 34% of the flag showing (brightest pixel #ffffff), accent 4.57:1
  no: {
    motif: "cross",
    ground: "#994b48",
    band: "#1d0c0b",
    flagAlpha: 0.34,
    accent: "#de0e2c",
    stripes: ["#ed2939", "#002664", "#ffffff"],
    glow: ["#002664", "#002664"],
  },
  // #00247d: ground 4.53:1, band 4.56:1 with 31% of the flag showing (brightest pixel #ffffff), accent 12.42:1
  nz: {
    motif: "diagonal",
    ground: "#405f9c",
    band: "#0a111f",
    flagAlpha: 0.31,
    accent: "#00247d",
    stripes: ["#00247d", "#c8102e", "#fffeff"],
    glow: ["#c8102e", "#c8102e"],
  },
  // #ef2d29: ground 4.62:1, band 4.51:1 with 28% of the flag showing (brightest pixel #ffffff), accent 4.67:1
  om: {
    motif: "horizontal",
    ground: "#893e36",
    band: "#1d0c0a",
    flagAlpha: 0.28,
    accent: "#dd0b15",
    stripes: ["#ef2d29", "#009025", "#ffffff"],
    glow: ["#009025", "#009025"],
  },
  // #0000ab: ground 4.62:1, band 4.53:1 with 32% of the flag showing (brightest pixel #ffffff), accent 12.11:1
  pa: {
    motif: "horizontal",
    ground: "#415e9c",
    band: "#0b111f",
    flagAlpha: 0.32,
    accent: "#0000ab",
    stripes: ["#ffffff", "#0000ab", "#db0000"],
    glow: ["#db0000", "#db0000"],
  },
  // #d91023: ground 4.52:1, band 4.6:1 with 30% of the flag showing (brightest pixel #ffffff), accent 4.75:1
  pe: {
    motif: "vertical",
    ground: "#8c403b",
    band: "#1d0c0b",
    flagAlpha: 0.3,
    accent: "#d91023",
    stripes: ["#d91023", "#ffffff"],
    glow: ["#d91023", "#d91023"],
  },
  // #0038a8: ground 4.51:1, band 4.55:1 with 31% of the flag showing (brightest pixel #ffffff), accent 9.03:1
  ph: {
    motif: "diagonal",
    ground: "#3f5f9c",
    band: "#0a111f",
    flagAlpha: 0.31,
    accent: "#0038a8",
    stripes: ["#0038a8", "#ce1126", "#ffffff"],
    glow: ["#ce1126", "#ce1126"],
  },
  // #0c590b: ground 4.57:1, band 4.51:1 with 31% of the flag showing (brightest pixel #ffffff), accent 7.85:1
  pk: {
    motif: "vertical",
    ground: "#30662d",
    band: "#091509",
    flagAlpha: 0.31,
    accent: "#0c590b",
    stripes: ["#0c590b", "#ffffff"],
    glow: ["#0c590b", "#0c590b"],
  },
  // #dc143c: ground 4.6:1, band 4.55:1 with 30% of the flag showing (brightest pixel #ffffff), accent 4.57:1
  pl: {
    motif: "horizontal",
    ground: "#893c3f",
    band: "#1d0c0c",
    flagAlpha: 0.3,
    accent: "#dc143c",
    stripes: ["#ffffff", "#dc143c"],
    glow: ["#dc143c", "#dc143c"],
  },
  // #ed0000: ground 4.53:1, band 4.51:1 with 31% of the flag showing (brightest pixel #ffffff), accent 4.55:1
  pr: {
    motif: "horizontal",
    ground: "#93463c",
    band: "#1d0c0a",
    flagAlpha: 0.31,
    accent: "#e20000",
    stripes: ["#ed0000", "#0050f0", "#ffffff"],
    glow: ["#0050f0", "#0050f0"],
  },
  // #ff0000: ground 4.52:1, band 4.51:1 with 31% of the flag showing (brightest pixel #ffffff), accent 4.59:1
  pt: {
    motif: "vertical",
    ground: "#93463c",
    band: "#1d0c0a",
    flagAlpha: 0.31,
    accent: "#e10000",
    stripes: ["#ff0000", "#006600"],
    glow: ["#006600", "#006600"],
  },
  // #0038a8: ground 4.59:1, band 4.57:1 with 29% of the flag showing (brightest pixel #ffffff), accent 9.03:1
  py: {
    motif: "horizontal",
    ground: "#395995",
    band: "#0a111f",
    flagAlpha: 0.29,
    accent: "#0038a8",
    stripes: ["#d52b1e", "#0038a8", "#ffffff"],
    glow: ["#d52b1e", "#d52b1e"],
  },
  // #8d1b3d: ground 4.62:1, band 4.53:1 with 32% of the flag showing (brightest pixel #ffffff), accent 8.16:1
  qa: {
    motif: "horizontal",
    ground: "#8e4151",
    band: "#1d0c0f",
    flagAlpha: 0.32,
    accent: "#8d1b3d",
    stripes: ["#8d1b3d", "#ffffff"],
    glow: ["#8d1b3d", "#8d1b3d"],
  },
  // #00319c: ground 4.61:1, band 4.56:1 with 27% of the flag showing (brightest pixel #ffde00), accent 10.02:1
  ro: {
    motif: "vertical",
    ground: "#2d4b86",
    band: "#0a111f",
    flagAlpha: 0.27,
    accent: "#00319c",
    stripes: ["#00319c", "#de2110", "#ffde00"],
    glow: ["#de2110", "#ffde00"],
  },
  // #c6363c: ground 4.54:1, band 4.57:1 with 32% of the flag showing (brightest pixel #ffffff), accent 4.82:1
  rs: {
    motif: "horizontal",
    ground: "#964846",
    band: "#1d0c0b",
    flagAlpha: 0.32,
    accent: "#c6363c",
    stripes: ["#ffffff", "#c6363c", "#0c4076"],
    glow: ["#0c4076", "#0c4076"],
  },
  // #0039a6: ground 4.59:1, band 4.58:1 with 29% of the flag showing (brightest pixel #ffffff), accent 9.01:1
  ru: {
    motif: "horizontal",
    ground: "#395995",
    band: "#0a111f",
    flagAlpha: 0.29,
    accent: "#0039a6",
    stripes: ["#ffffff", "#0039a6", "#d52b1e"],
    glow: ["#d52b1e", "#d52b1e"],
  },
  // #00a1de: ground 4.52:1, band 4.57:1 with 29% of the flag showing (brightest pixel #fad201), accent 4.59:1
  rw: {
    motif: "horizontal",
    ground: "#005780",
    band: "#04141d",
    flagAlpha: 0.29,
    accent: "#0075b0",
    stripes: ["#00a1de", "#fad201", "#20603d"],
    glow: ["#fad201", "#20603d"],
  },
  // #165d31: ground 4.54:1, band 4.54:1 with 30% of the flag showing (brightest pixel #ffffff), accent 7.28:1
  sa: {
    motif: "horizontal",
    ground: "#23673b",
    band: "#07150b",
    flagAlpha: 0.3,
    accent: "#165d31",
    stripes: ["#165d31"],
    glow: ["#165d31", "#165d31"],
  },
  // #005293: ground 4.52:1, band 4.52:1 with 23% of the flag showing (brightest pixel #fecb00), accent 7.32:1
  se: {
    motif: "cross",
    ground: "#0c467b",
    band: "#07121e",
    flagAlpha: 0.23,
    accent: "#005293",
    stripes: ["#005293", "#fecb00"],
    glow: ["#fecb00", "#fecb00"],
  },
  // #0000bf: ground 4.51:1, band 4.55:1 with 32% of the flag showing (brightest pixel #ffffff), accent 10.98:1
  si: {
    motif: "horizontal",
    ground: "#44619f",
    band: "#0b111f",
    flagAlpha: 0.32,
    accent: "#0000bf",
    stripes: ["#0000bf", "#d50000", "#ffffff"],
    glow: ["#d50000", "#d50000"],
  },
  // #ee1c25: ground 4.56:1, band 4.55:1 with 31% of the flag showing (brightest pixel #ffffff), accent 4.5:1
  sk: {
    motif: "horizontal",
    ground: "#93463f",
    band: "#1d0c0a",
    flagAlpha: 0.31,
    accent: "#e30019",
    stripes: ["#ee1c25", "#ffffff", "#0b4ea2"],
    glow: ["#0b4ea2", "#0b4ea2"],
  },
  // #bc0000: ground 4.62:1, band 4.54:1 with 23% of the flag showing (brightest pixel #ffff00), accent 6.13:1
  sn: {
    motif: "vertical",
    ground: "#793027",
    band: "#1d0c0a",
    flagAlpha: 0.23,
    accent: "#bc0000",
    stripes: ["#0b7226", "#bc0000", "#ffff00"],
    glow: ["#0b7226", "#ffff00"],
  },
  // #0f47af: ground 4.56:1, band 4.6:1 with 27% of the flag showing (brightest pixel #ffffff), accent 7.57:1
  ss: {
    motif: "horizontal",
    ground: "#33548f",
    band: "#0a111f",
    flagAlpha: 0.27,
    accent: "#0f47af",
    stripes: ["#0f47af", "#078930", "#000001"],
    glow: ["#078930", "#078930"],
  },
  // #0f47af: ground 4.52:1, band 4.55:1 with 31% of the flag showing (brightest pixel #ffffff), accent 7.57:1
  sv: {
    motif: "horizontal",
    ground: "#3b5c98",
    band: "#0a111f",
    flagAlpha: 0.31,
    accent: "#0f47af",
    stripes: ["#0f47af", "#ffffff"],
    glow: ["#0f47af", "#0f47af"],
  },
  // #a51931: ground 4.59:1, band 4.51:1 with 35% of the flag showing (brightest pixel #f4f5f8), accent 6.91:1
  th: {
    motif: "horizontal",
    ground: "#96484b",
    band: "#1d0c0c",
    flagAlpha: 0.35,
    accent: "#a51931",
    stripes: ["#a51931", "#2d2a4a", "#f4f5f8"],
    glow: ["#2d2a4a", "#2d2a4a"],
  },
  // #e70013: ground 4.54:1, band 4.56:1 with 31% of the flag showing (brightest pixel #ffffff), accent 4.63:1
  tn: {
    motif: "emblem",
    ground: "#8c4039",
    band: "#1d0c0a",
    flagAlpha: 0.31,
    accent: "#e00006",
    stripes: ["#e70013", "#ffffff"],
    glow: ["#e70013", "#e70013"],
  },
  // #c10000: ground 4.57:1, band 4.58:1 with 32% of the flag showing (brightest pixel #ffffff), accent 5.89:1
  to: {
    motif: "cross",
    ground: "#8f443a",
    band: "#1d0c0a",
    flagAlpha: 0.32,
    accent: "#c10000",
    stripes: ["#c10000", "#ffffff"],
    glow: ["#c10000", "#c10000"],
  },
  // #e30a17: ground 4.51:1, band 4.51:1 with 31% of the flag showing (brightest pixel #ffffff), accent 4.63:1
  tr: {
    motif: "diagonal",
    ground: "#8c4039",
    band: "#1d0c0a",
    flagAlpha: 0.31,
    accent: "#df0012",
    stripes: ["#e30a17", "#ffffff"],
    glow: ["#e30a17", "#e30a17"],
  },
  // #e00000: ground 4.57:1, band 4.59:1 with 31% of the flag showing (brightest pixel #ffffff), accent 4.61:1
  tt: {
    motif: "diagonal",
    ground: "#8c4137",
    band: "#1d0c0a",
    flagAlpha: 0.31,
    accent: "#e00000",
    stripes: ["#e00000", "#000001", "#fffefe"],
    glow: ["#e00000", "#e00000"],
  },
  // #ff0000: ground 4.66:1, band 4.58:1 with 36% of the flag showing (brightest pixel #ffffff), accent 4.59:1
  tw: {
    motif: "horizontal",
    ground: "#9c4f44",
    band: "#1d0c0a",
    flagAlpha: 0.36,
    accent: "#e10000",
    stripes: ["#ff0000", "#000095"],
    glow: ["#000095", "#000095"],
  },
  // #0099ff: ground 4.61:1, band 4.54:1 with 28% of the flag showing (brightest pixel #ffff00), accent 4.54:1
  tz: {
    motif: "diagonal",
    ground: "#185589",
    band: "#07131e",
    flagAlpha: 0.28,
    accent: "#0070d2",
    stripes: ["#000001", "#009900", "#0099ff"],
    glow: ["#009900", "#009900"],
  },
  // #0057b8: ground 4.61:1, band 4.52:1 with 21% of the flag showing (brightest pixel #ffd700), accent 6.3:1
  ua: {
    motif: "horizontal",
    ground: "#163f76",
    band: "#09121f",
    flagAlpha: 0.21,
    accent: "#0057b8",
    stripes: ["#0057b8", "#ffd700"],
    glow: ["#ffd700", "#ffd700"],
  },
  // #de3908: ground 4.57:1, band 4.58:1 with 16% of the flag showing (brightest pixel #ffffff), accent 4.64:1
  ug: {
    motif: "horizontal",
    ground: "#692212",
    band: "#1d0c09",
    flagAlpha: 0.16,
    accent: "#d32d00",
    stripes: ["#ffe700", "#000001", "#de3908"],
    glow: ["#ffe700", "#ffe700"],
  },
  // #bd3d44: ground 4.61:1, band 4.57:1 with 33% of the flag showing (brightest pixel #ffffff), accent 4.91:1
  us: {
    motif: "horizontal",
    ground: "#964848",
    band: "#1d0c0c",
    flagAlpha: 0.33,
    accent: "#bd3d44",
    stripes: ["#bd3d44", "#ffffff", "#192f5d"],
    glow: ["#192f5d", "#192f5d"],
  },
  // #0038a8: ground 4.53:1, band 4.58:1 with 32% of the flag showing (brightest pixel #ffffff), accent 9.03:1
  uy: {
    motif: "horizontal",
    ground: "#3f5f9c",
    band: "#0a111f",
    flagAlpha: 0.32,
    accent: "#0038a8",
    stripes: ["#ffffff", "#0038a8"],
    glow: ["#0038a8", "#0038a8"],
  },
  // #1eb53a: ground 4.53:1, band 4.59:1 with 25% of the flag showing (brightest pixel #ffffff), accent 4.58:1
  uz: {
    motif: "horizontal",
    ground: "#205b25",
    band: "#091509",
    flagAlpha: 0.25,
    accent: "#008200",
    stripes: ["#ffffff", "#1eb53a", "#0099b5"],
    glow: ["#0099b5", "#0099b5"],
  },
  // #f4f100: ground 4.6:1, band 4.55:1 with 31% of the flag showing (brightest pixel #f4f100), accent 4.65:1
  vc: {
    motif: "vertical",
    ground: "#585600",
    band: "#131303",
    flagAlpha: 0.31,
    accent: "#787000",
    stripes: ["#f4f100", "#199a00", "#0058aa"],
    glow: ["#199a00", "#0058aa"],
  },
  // #cf142b: ground 4.5:1, band 4.58:1 with 26% of the flag showing (brightest pixel #ffffff), accent 5.08:1
  ve: {
    motif: "horizontal",
    ground: "#863a38",
    band: "#1d0c0b",
    flagAlpha: 0.26,
    accent: "#cf142b",
    stripes: ["#ffcc00", "#cf142b", "#00247d"],
    glow: ["#ffcc00", "#00247d"],
  },
  // #000066: ground 4.52:1, band 4.56:1 with 31% of the flag showing (brightest pixel #ffffff), accent 16.14:1
  vg: {
    motif: "diagonal",
    ground: "#415e9c",
    band: "#0b111f",
    flagAlpha: 0.31,
    accent: "#000066",
    stripes: ["#000066", "#c8102e", "#fefefe"],
    glow: ["#c8102e", "#c8102e"],
  },
  // #f4c53d: ground 4.51:1, band 4.56:1 with 18% of the flag showing (brightest pixel #ffffff), accent 4.58:1
  vi: {
    motif: "diagonal",
    ground: "#533800",
    band: "#171103",
    flagAlpha: 0.18,
    accent: "#936700",
    stripes: ["#ffffff", "#f4c53d"],
    glow: ["#f4c53d", "#f4c53d"],
  },
  // #ce1126: ground 4.56:1, band 4.52:1 with 34% of the flag showing (brightest pixel #ffffff), accent 5.15:1
  ws: {
    motif: "horizontal",
    ground: "#994b47",
    band: "#1d0c0b",
    flagAlpha: 0.34,
    accent: "#ce1126",
    stripes: ["#ce1126", "#002b7f"],
    glow: ["#002b7f", "#002b7f"],
  },
  // #007847: ground 4.5:1, band 4.52:1 with 32% of the flag showing (brightest pixel #ffffff), accent 5.09:1
  za: {
    motif: "diagonal",
    ground: "#1c7247",
    band: "#06160c",
    flagAlpha: 0.32,
    accent: "#007847",
    stripes: ["#007847", "#000c8a", "#e1392d"],
    glow: ["#000c8a", "#e1392d"],
  },
  // #198a00: ground 4.52:1, band 4.56:1 with 40% of the flag showing (brightest pixel #ef7d00), accent 4.66:1
  zm: {
    motif: "vertical",
    ground: "#24581d",
    band: "#0a1508",
    flagAlpha: 0.4,
    accent: "#048100",
    stripes: ["#198a00", "#ef7d00", "#000001"],
    glow: ["#ef7d00", "#ef7d00"],
  },
  // #006400: ground 4.62:1, band 4.58:1 with 17% of the flag showing (brightest pixel #ffffff), accent 6.82:1
  zw: {
    motif: "diagonal",
    ground: "#0f470d",
    band: "#091509",
    flagAlpha: 0.17,
    accent: "#006400",
    stripes: ["#006400", "#ffd200", "#ffffff"],
    glow: ["#ffd200", "#ffd200"],
  },
};
