/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FieldRouteImport } from './routes/field'
import { Route as ProjectionsRouteImport } from './routes/projections'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as TrackRouteImport } from './routes/track'
import { Route as AthleteDiscKeyNameRouteImport } from './routes/athlete.$discKey.$name'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FieldRoute = FieldRouteImport.update({
  id: '/field',
  path: '/field',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectionsRoute = ProjectionsRouteImport.update({
  id: '/projections',
  path: '/projections',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const AthleteDiscKeyNameRoute = AthleteDiscKeyNameRouteImport.update({
  id: '/athlete/$discKey/$name',
  path: '/athlete/$discKey/$name',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/field': typeof FieldRoute
  '/projections': typeof ProjectionsRoute
  '/schedule': typeof ScheduleRoute
  '/track': typeof TrackRoute
  '/athlete/$discKey/$name': typeof AthleteDiscKeyNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/field': typeof FieldRoute
  '/projections': typeof ProjectionsRoute
  '/schedule': typeof ScheduleRoute
  '/track': typeof TrackRoute
  '/athlete/$discKey/$name': typeof AthleteDiscKeyNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/field': typeof FieldRoute
  '/projections': typeof ProjectionsRoute
  '/schedule': typeof ScheduleRoute
  '/track': typeof TrackRoute
  '/athlete/$discKey/$name': typeof AthleteDiscKeyNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/field'
    | '/projections'
    | '/schedule'
    | '/track'
    | '/athlete/$discKey/$name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/field'
    | '/projections'
    | '/schedule'
    | '/track'
    | '/athlete/$discKey/$name'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/field'
    | '/projections'
    | '/schedule'
    | '/track'
    | '/athlete/$discKey/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  FieldRoute: typeof FieldRoute
  ProjectionsRoute: typeof ProjectionsRoute
  ScheduleRoute: typeof ScheduleRoute
  TrackRoute: typeof TrackRoute
  AthleteDiscKeyNameRoute: typeof AthleteDiscKeyNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/field': {
      id: '/field'
      path: '/field'
      fullPath: '/field'
      preLoaderRoute: typeof FieldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projections': {
      id: '/projections'
      path: '/projections'
      fullPath: '/projections'
      preLoaderRoute: typeof ProjectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athlete/$discKey/$name': {
      id: '/athlete/$discKey/$name'
      path: '/athlete/$discKey/$name'
      fullPath: '/athlete/$discKey/$name'
      preLoaderRoute: typeof AthleteDiscKeyNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  FieldRoute: FieldRoute,
  ProjectionsRoute: ProjectionsRoute,
  ScheduleRoute: ScheduleRoute,
  TrackRoute: TrackRoute,
  AthleteDiscKeyNameRoute: AthleteDiscKeyNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
